# docker-compose.yml
# ACCOUNT=123456 NAPCAT_UID=$(id -u) NAPCAT_GID=$(id -g) docker-compose -f ./compose/dice.yml up -d 
services:
  dice:
    image: shiaworkshop/dice:latest
    container_name: dice-main
    stdin_open: true
    tty: true
    volumes:
      - "./Dice:/app/Dice"
      - "./napcat/config:/app/napcat/config"
    environment:
      - ACCOUNT=${ACCOUNT}
    networks:
      - dice_network
    depends_on:
      - napcat

  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    ports:
      - "6099:6099"
    volumes:
      - "./napcat/config:/app/napcat/config"
      - "./napcat/QQ_DATA:/app/.config/QQ"
      - "./Dice:/app/Dice"
    environment:
      - NAPCAT_UID=${NAPCAT_UID:-1000}
      - NAPCAT_GID=${NAPCAT_GID:-1000}
      - ACCOUNT=${ACCOUNT}
      - MODE=dice
    networks:
      - dice_network
    mac_address: "02:42:ac:11:00:02"

networks:
  dice_network:
    driver: bridge