# Q2TG & NapCat Docker Compose 配置文件
# 启动命令: NAPCAT_UID=$(id -u) NAPCAT_GID=$(id -g) docker-compose -f ./compose/q2tg.yml up -d
services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql:/var/lib/postgresql/data
  napcat:
    container_name: napcat
    image: mlikiowa/napcat-docker:latest
    restart: always
    environment:
      - NAPCAT_UID=${NAPCAT_UID:-1000}
      - NAPCAT_GID=${NAPCAT_GID:-1000}
      - MODE=q2tg
    ports:
      - 6099:6099
      - 3001:3001
    volumes:
      - ./napcat:/app/napcat
      - ./ntqq:/app/.config/QQ
    networks:
      - q2tg_network
    mac_address: "02:42:ac:11:00:02"

  q2tg:
    container_name: q2tg
    image: clansty/q2tg:rainbowcat
    restart: unless-stopped
    volumes:
      - ./napcat:/app/napcat
      - ./ntqq:/app/.config/QQ
    networks:
      - q2tg_network

networks:
  q2tg_network:
    driver: bridge